#!/bin/csh -f

set TAR_FILE=warmup1.tar

if(-f $TAR_FILE) then
  /bin/rm -rf $TAR_FILE
endif

make clean
make server
make client

make clean
make

tar cvf $TAR_FILE Makefile README *.c *.cc *.h
gzip $TAR_FILE

