#!/bin/csh -f

set port=13212

./client -g nunki.usc.edu:$port /etc/passwd
./client -g nunki.usc.edu:$port /home/scf-22/csci551b/hello
./client -g localhost:$port /home/scf-22/csci551b/tmp/hello
./client -g localhost:$port Makefile
./client -g localhost:$port /usr/lsd/openssl/default/include/openssl/md5.h
./client -g localhost:$port /usr/lsd/openssl/default/bin/openssl
./client -g localhost:$port /etc/shadow
./client -g localhost:$port /etc/hosts.equiv


