#!/bin/csh -f

set srcdir=~csci530/public/hw2

foreach f ( 0 1 2 3 4 5 6 )
  echo "===> $srcdir/f$f"
  ./hw2 sha1 $srcdir/f$f > f$f.sha1
  diff $srcdir/f$f.sha1 f$f.sha1
end

/bin/rm -f f*.sha1

foreach f ( 7 8 9 )
  echo "===> $srcdir/f$f"
  cat $srcdir/f$f | ./hw2 sha1 > f$f.sha1
  diff $srcdir/f$f.sha1 f$f.sha1
end

/bin/rm -f f*.sha1

