#!/bin/csh -f

set srcdir=~csci530/public/hw4

#
# (C1)
# for the following commands, each correct answer gets 1 point
# "diff" command should produce nothing
#
/bin/rm -f f?.verify
foreach f (0 1 2 3 4 5 6 7 8 9)
  echo "===> $srcdir/f$f"
  ./hw4 sign -so=./libhw4sc.so $srcdir/f$f | \
  ./hw4 verify -so=./libhw4sc.so > f$f.verify
  diff $srcdir/f$f.verify f$f.verify
end
/bin/rm -f f?.verify

#
# (C2)
# for the following commands, each correct answer gets 1 point
# use randomly generated "secret.c"
#
/bin/rm -f f?.sign f?.verify
foreach f (1 3 5 7 9)
  echo "===> $srcdir/f$f"
  /bin/rm -f secret.c
  cp secret.c.$f secret.c
  /bin/rm -f *.o
  make clean
  make smartcard
  make hw4
  ./hw4 sign -so=./libhw4sc.so $srcdir/f$f > f$f.sign
  ./hw4 verify -so=./libhw4sc.so f$f.sign > f$f.verify
  echo "----------------------------------------------------"
  echo "---> diff $srcdir/f$f.verify f$f.verify"
  diff $srcdir/f$f.verify f$f.verify
  echo "make sure there's no difference above "
  echo -n "press <CR> to continue..."
  set foo=$<
  clear
end
#
# make sure the signatures are different from what's
# in $srcdir, if any of the signatures are the same
# as what's in $srcdir, the tests in (C2) were invalid
# and a total of zero point should be given to (C2)
#
foreach f (1 3 5 7 9)
  echo "===> $srcdir/f$f"
  diff $srcdir/f$f.sign f$f.sign
  echo "make sure there's a difference above "
  echo -n "press <CR> to continue..."
  set foo=$<
  clear
end
/bin/rm -f f?.sign f?.verify
/bin/rm -f secret.c
cp ~csci530/public/hw4/secret.c .
/bin/rm -f *.o
make clean
make smartcard
make hw4

