#!/bin/csh -f

set srcdir=~csci530/public/hw4

if( -f secret.c) then
  mv secret.c secret.c.submitted
endif
cp $srcdir/secret.c .

/bin/rm -f *.o
make clean
make smartcard
make hw4

foreach f ( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
  ./hw4 secret > secret.c.$f
end

