#!/bin/csh -f

set srcdir=~csci530/public/hw4

#
# (E1)
# for the following commands, each correct answer gets 1 point
# please use "yesnomaybe" as the passphrase for all tests here
# "diff" command should produce nothing
#
/bin/rm -f f?.dat
echo "----------------------------------------------"
echo "passphrase = yesnomaybe"
echo "----------------------------------------------"
foreach f (0 2 4 6 8)
  echo "===> $srcdir/f$f"
  ./hw4 dec -so=./libhw4sc.so $srcdir/f$f.1.enc > f$f.dat
  diff $srcdir/f$f f$f.dat
end

#
# (E2)
# for the following commands, each correct answer gets 1 point
# please use "tomorrow" as the passphrase for all tests here
# "diff" command should produce nothing
#
/bin/rm -f f?.dat
echo "----------------------------------------------"
echo "passphrase = tomorrow"
echo "----------------------------------------------"
foreach f (1 3 5 7 9)
  echo "===> $srcdir/f$f"
  ./hw4 dec -so=./libhw4sc.so $srcdir/f$f.2.enc > f$f.dat
  diff $srcdir/f$f f$f.dat
end
/bin/rm -f f?.dat

