#! /bin/csh

foreach file(./*.cpp)
  set newfile=`echo $file|sed -n s/cpp/cc/p`
  echo "renaming $file with $newfile"
  mv $file $newfile
end

foreach file (`ls ./*.cc *.h`)
  if (-d $file) then
    #do not do any thing 
  else if( $file == "./clean" ) then
   #do not do any thing
  else
    echo "running dos2unix on $file"
    /usr/bin/dos2unix $file $file
  endif
end

