#!/bin/csh -f

set srcdir=/auto/home-scf-22/csci530/public/hw1

/bin/rm -f f*.dat
#generate decoding files using openssl
foreach f(0 1 2 3 4 5 6 7 8 9)
  echo "===> $srcdir/f$f"
  openssl enc -d -base64 -in $srcdir/f$f.b64 > o$f.dat
end

foreach f(0 1 2 3 4 5 6 7 8 9)
  ./hw1 dec-base64 $srcdir/f$f.b64 > f$f.dat
  diff f$f.dat o$f.dat
end

/bin/rm -f f*.dat
/bin/rm -f o*.dat

echo "-----------------------------"

/bin/rm -f f*.dat
foreach f (5 6 7 9)
  echo "===> $srcdir/f$f"
  ./hw1 dec-base64 $srcdir/f$f.b64 > f$f.dat
  diff $srcdir/f$f f$f.dat
end

echo "-----------------------------"

foreach f (0 1 2 3 9)
    echo "===> $srcdir/f$f"
    cat $srcdir/f$f.b64 | ./hw1 dec-base64 > f$f.dat
    diff $srcdir/f$f f$f.dat
end

echo "-----------------------------"

/bin/rm -f f*.dat
foreach f (100 101)
    echo "===> $srcdir/f$f"
    cat $srcdir/f$f.b64 | ./hw1 dec-base64 > f$f.dat
    diff $srcdir/f$f f$f.dat
end

/bin/rm -f f*.dat
