#!/bin/csh -f

set srcdir=/auto/home-scf-22/csci530/public/hw1

set srcdir=~csci530/public/hw1

/bin/rm -f f*.dat
foreach f (0 1 2 3 4 5 6 7 8 9)
	echo "===> $srcdir/f$f"
	./hw1 enc-base64 $srcdir/f$f | ./hw1 dec-base64 > f$f.dat
	diff $srcdir/f$f f$f.dat
end
/bin/rm -f f*.dat

